%Debug_FlyBubblePipeline.m

modpath;


%% parameters
settingsdir = '/groups/branson/home/robiea/Code_versioned/FlyTrackerPipeline/settings';

analysis_protocol = '20210228_flybubble_dickson_locomotionGtACR1';
% analysis_protocol = '20210219_flybubble_dickson_nochrGtACR1testing'

params = {'settingsdir',settingsdir,...
    'analysis_protocol',analysis_protocol, ...
    'forcecompute',true,...
    'doautomaticchecksincoming',false,...
    'doflytracking',false, ...
    'doregistration',true,...
    'doledonoffdetection',false,...
    'dosexclassification',false,...
    'dotrackwings',false,...
    'docomputeperframefeatures',false,...
    'docomputehoghofperframefeatures',false,...
    'dojaabadetect',false,...
    'docomputeperframestats',false,...
    'doplotperframestats',false,...
    'domakectraxresultsmovie',false,...
    'doextradiagnostics',false,...
    'doanalysisprotocol',isunix,...
    'doautomaticcheckscomplete',false};

%% experiment directory
% manually tracked by Alice 
% expdir = '/groups/branson/home/robiea/Projects_data/FlyDisco/Bubble_data/locomotionGtACR1_24_EXT_VGLUT-GAL4_RigA_20210226T095136';
% expdir = '/groups/branson/home/robiea/Projects_data/FlyDisco/Bubble_data/20210301_calibration/socialCsChr_GMR_72C11_AE_01_CsChrimson_RigD_20191114T172654';
% expdir = '/groups/branson/home/robiea/Projects_data/FlyDisco/Bubble_data/20210301_calibration/nochr_TrpA71G01_Unknown_RigA_20201216T162938';
expdir = '/groups/branson/home/robiea/Projects_data/FlyDisco/Bubble_data/runbypipeline/locomotionGtACR1_24_EXT_VGLUT-GAL4_RigA_20210226T095136';
%% run
% for i = 1:numel(explist)
%     expdir = explist{i};
% [success,msgs,stage] = FlyBubblePipeline(expdir,params{:});
% end

[success,msgs,stage] = FlyBubblePipelineWithFT(expdir,params{:});
