function trx = FlyBowlClassifySex(expdir,varargin)

[analysis_protocol,settingsdir,sexclassificationfilestr,datalocparamsfilestr] = ...
  myparse(varargin,...
  'analysis_protocol','current',...
  'settingsdir','/groups/branson/bransonlab/projects/olympiad/FlyBowlAnalysis/settings',...
  'sexclassificationfilestr','sexclassification_params.txt',...
  'datalocparamsfilestr','dataloc_params.txt');
