function result = FlyDiscoStageNames()

% Return a cell string of all the FlyDisco stage names

stage_function_from_name = FlyDiscoStageFunctionFromName() ;
result = fieldnames(stage_function_from_name) ;
% result = { ...
%   'automaticchecksincoming' , ...
%   'flytracking', ...
%   'addpflies' , ...
%   'registration' , ...
%   'ledonoffdetection', ...
%   'sexclassification', ...
%   'apt', ...
%   'computeperframefeatures', ...
%   'computehoghofperframefeatures', ...
%   'jaabadetect' , ...
%   'locomotionmetrics', ...
%   'computeperframestats' , ...
%   'plotperframestats' , ...
%   'makectraxresultsmovie' , ...
%   'makeaptresultsmovie', ...
%   'automaticcheckscomplete' }' ; 

end
