function result = FlyDiscoStageNames()

% Return a cell string of all the FlyDisco stage names

result = { ...
  'automaticchecksincoming' , ...
  'flytracking', ...
  'addpflies' , ...
  'registration' , ...
  'ledonoffdetection', ...
  'sexclassification', ...
  'computeperframefeatures', ...
  'computehoghofperframefeatures', ...
  'jaabadetect' , ...
  'locomotionmetrics', ...
  'computeperframestats' , ...
  'plotperframestats' , ...
  'makectraxresultsmovie' , ...
  'apt', ...
  'makeaptresultsmovie', ...
  'automaticcheckscomplete' }' ; 

end
