function FlyDiscoPipelineStage(expdir, ...
                               stage_name, ...
                               do_run, ...
                               required_file_names_from_stage_name, ...
                               debug, ...
                               settingsdir, ...
                               analysis_protocol_name, ...
                               stage_function, ...
                               stage_args_from_stage_name)
                           
    % General function for running 'typical' pipeline stage.       
    do_run_stage = do_run.(stage_name) ;
    if is_on_or_force(do_run_stage) ,
        do_force = is_force(do_run_stage) ;
        required_files_for_stage = required_file_names_from_stage_name.(stage_name) ;
        are_some_files_missing_on_entry = CheckForMissingFilesExplicit(expdir, required_files_for_stage) ;
        do_run_stage_for_reals = do_force || are_some_files_missing_on_entry ;
        if do_run_stage_for_reals ,
            % Write a header for this stage to the 'log'
            timestamp = datestr(now(),'yyyymmddTHHMMSS') ;
            real_analysis_protocol_name = GetRealAnalysisProtocol(analysis_protocol_name, settingsdir) ;
            fprintf('\n\n***\nRunning %s() for stage %s with analysis protocol %s at %s\n', ...
                    char(stage_function), stage_name, real_analysis_protocol_name, timestamp) ;          
            %fprintf('In stage %s, calling core function %s()...\n', stage_name, char(stage_function));
            stage_additional_arguments = stage_args_from_stage_name.(stage_name) ;
            feval(stage_function, ...
                  expdir, ...
                  'settingsdir', settingsdir, ...
                  'analysis_protocol', analysis_protocol_name, ...
                  'forcecompute', do_force, ...
                  'do_run', do_run, ...
                  'debug', debug, ...
                  stage_additional_arguments{:}) ;
            %fprintf('In stage %s, core function %s() has returned.\n', stage_name, char(stage_function));
            end_timestamp = datestr(now(),'yyyymmddTHHMMSS') ;
            fprintf('Done running %s() for stage %s with analysis protocol %s at %s\n', ...
                    char(stage_function), stage_name, real_analysis_protocol_name, end_timestamp) ;          
        end

        % Make sure output files exist
        [are_some_files_missing_on_exit, missing_file_names] = CheckForMissingFilesExplicit(expdir, required_files_for_stage) ;
        if are_some_files_missing_on_exit ,
            msgs = cellfun(@(file_name)(sprintf('Missing %s file %s', stage_name, file_name)), missing_file_names, 'UniformOutput', false) ;
            fprintf('Stage %s failed:\n', stage_name);
            flydisco_pipeline_error(stage_name, msgs) ;
        end
    end
end
