function result = FlyDiscoPipelineDefaultAnalysisParameters()
    % This is used by both FlyDiscoAnalysis() and FlyDiscoCaboose(), that's why
    % it's a standalone zero-arg function, aka a global constant.
    
    % Set the default analysis parameters
    result = ...
        {'datalocparamsfilestr','dataloc_params.txt',...
        'automaticchecksincoming_params',{},...
        'registration_params',{},...
        'sexclassification_params',{},...
        'computeperframefeatures_params',{},...
        'computeperframestats_params',{},...
        'computehoghofperframefeatures_params',{},...
        'plotperframestats_params',{},...
        'makectraxresultsmovie_params',{},...
        'automaticcheckscomplete_params',{},...
        'doautomaticchecksincoming','force',...
        'doflytracking','on', ...
        'doregistration','on',...
        'doledonoffdetection','on',...
        'dosexclassification','on',...
        'docomputeperframefeatures','on',...
        'docomputehoghofperframefeatures','off',...
        'dojaabadetect','on',...
        'docomputeperframestats','off',...
        'doplotperframestats','off',...
        'domakectraxresultsmovie','on',...
        'doautomaticcheckscomplete','force',...
        'requiredfiles_start',{},...
        'requiredfiles_automaticchecksincoming',{'automaticchecksincomingresultsfilestr'},...
        'requiredfiles_flytracker',{'ctraxfilestr'},...
        'requiredfiles_registration',{'trxfilestr','registrationmatfilestr','registrationtxtfilestr','registrationimagefilestr'},...
        'requiredfiles_ledonoffdetection',{'indicatordatafilestr'},...
        'requiredfiles_sexclassification',{'sexclassifierdiagnosticsfilestr'},...
        'requiredfiles_wingtracking',{'wingtrxfilestr'},...
        'requiredfiles_computeperframefeatures',{'perframedir', 'PERFRAMEMATFILES'},...
        'requiredfiles_computehoghofperframefeatures',{'hs_sup_01_01_1.mat','hf_01_01_1.mat'},...
        'requiredfiles_computeperframestats',{'statsperframetxtfilestr','statsperframematfilestr'},...
        'requiredfiles_plotperframestats',{'figdir', 'statswebpagefilestr', 'ANALYSISPLOTS'},...
        'requiredfiles_makectraxresultsmovie',{'CTRAXRESULTSMOVIE'},...
        'requiredfiles_extradiagnostics',{'biasdiagnosticsimagefilestr','biasdiagnosticsfilestr','biasdiagnosticsmatfilestr',...
        'temperaturediagnosticsfilestr','bkgddiagnosticsimagefilestr','bkgddiagnosticsfilestr','bkgddiagnosticsmatfilestr',...
        'videodiagnosticsfilestr','videodiagnosticsmatfilestr','videodiagnosticsimagefilestr'},...
        'requiredfiles_analysisprotocol',{'analysis_protocol.txt'},...
        'requiredfiles_automaticcheckscomplete',{'automaticcheckscompleteresultsfilestr'} } ;
end
