function FlyDiscoPipelineStage(expdir, ...
                               stage_name, ...
                               do_run, ...
                               dataloc_params, ...
                               required_file_names_from_stage_name, ...
                               settingsdir, ...
                               analysis_protocol_name, ...
                               stage_function, ...
                               stage_additional_arguments)  %#ok<INUSD> 
                           
    % General function for running 'typical' pipeline stage.       
    do_run_stage = do_run.(stage_name) ;
    if is_on_or_force(do_run_stage) ,
        do_force = is_force(do_run_stage) ;
        required_files_for_stage = required_file_names_from_stage_name.(stage_name) ;
        are_some_files_missing_on_entry = CheckForMissingFilesExplicit(expdir, required_files_for_stage) ;
        do_run = do_force || are_some_files_missing_on_entry ;
        if do_run ,
            fprintf('In stage %s, calling core function %s()...\n', stage_name, char(stage_function));
            feval(stage_function, ...
                  expdir, ...
                  'settingsdir', settingsdir, ...
                  'analysis_protocol', analysis_protocol_name, ...
                  'forcecompute', do_force, ...
                  stage_additional_arguments{:}) ;
            fprintf('In stage %s, calling core function %s() has returned.\n', stage_name, char(stage_function));
        end

        % Make sure output files exist
        [are_some_files_missing_on_exit, missing_file_names] = CheckForMissingFilesExplicit(expdir, required_files_for_stage) ;
        if are_some_files_missing_on_exit ,
            msgs = cellfun(@(file_name)(sprintf('Missing %s file %s', stage_name, file_name)), missing_file_names, 'UniformOutput', false) ;
            fprintf('Stage %s failed:\n', stage_name);
            flydisco_pipeline_error(stage_name, msgs) ;
        end
    end
end
