function result = FlyDiscoPipelineDefaultAnalysisParameters()
    % This is a standalone zero-arg function, aka a global constant.
    
    % Set the default analysis parameters
    result = ...
        {'automaticchecksincoming_params',{},...
         'registration_params',{},...
         'sexclassification_params',{},...
         'computeperframefeatures_params',{},...
         'computeperframestats_params',{},...
         'computehoghofperframefeatures_params',{},...
         'plotperframestats_params',{},...
         'makectraxresultsmovie_params',{},...
         'aptresultsmovie_params',{},...
         'automaticcheckscomplete_params',{},...
         'doautomaticchecksincoming','force',...
         'doflytracking','on', ...
         'doaddpflies','off', ...
         'doregistration','on',...
         'doledonoffdetection','on',...
         'dosexclassification','on',...
         'docomputeperframefeatures','on',...
         'docomputehoghofperframefeatures','off',...
         'docomputeaptperframefeatures','off',...
         'dojaabadetect','on',...
         'docomputelocomotionmetrics','off',...
         'docomputeperframestats','off',...
         'doplotperframestats','off',...
         'domakectraxresultsmovie','on',...
         'doapt', 'off', ...
         'domakeaptresultsmovie','off', ...
         'doautomaticcheckscomplete','force',...
         'requiredfiles_start',{},...
         'requiredfiles_extradiagnostics',{'biasdiagnosticsimagefilestr','biasdiagnosticsfilestr','biasdiagnosticsmatfilestr',...
         'temperaturediagnosticsfilestr','bkgddiagnosticsimagefilestr','bkgddiagnosticsfilestr','bkgddiagnosticsmatfilestr',...
         'videodiagnosticsfilestr','videodiagnosticsmatfilestr','videodiagnosticsimagefilestr'},...
         'cluster_billing_account_name', '', ...
         'sshhost', '', ...
         'debug', false} ;
end
