function params = ReadAutoChecks(filename)
% alice robie 7/9/2024 - used code generated by chatGPT to read in text to get
% started
params = struct;

fileID = fopen(filename,'r');

% Read the file line by line
tline = fgetl(fileID);
while ischar(tline)
    % Split the line at the first comma
    splitLine = strsplit(tline, ',', 'CollapseDelimiters', false);

    % Assign the text after the variable name to the appropriate variable
    switch splitLine{1}
        case 'automated_pf'
            automated_pf = splitLine{2};
        case 'notes_curation'
            if ~isempty(splitLine{2})
                notes_curation = splitLine{2};
                tline = fgetl(fileID);

              
                if ischar(tline) && startsWith(tline, 'automated_pf_category')
                    splitLine = strsplit(tline, ',', 'CollapseDelimiters', false);
                    automated_pf_category = splitLine{2};
                    break;
                end
            else
                notes_curation = '';
                while true
                    tline = fgetl(fileID);
                    if ischar(tline) && startsWith(tline, 'automated_pf_category')
                        splitLine = strsplit(tline, ',', 'CollapseDelimiters', false);
                        automated_pf_category = splitLine{2};
                        break;
                    end
                    notes_curation = [notes_curation tline, ' ' ];
                end
            end
        case 'automated_pf_category'
            automated_pf_category = splitLine{2};

    end
    tline = fgetl(fileID);
end

% Close the file
fclose(fileID);

% Remove trailing newline from notes_curation
if exist('notes_curation','var')
    notes_curation = notes_curation(1:end-1);
end

% add variables to struct

if exist('automated_pf','var')
    params.automated_pf = automated_pf;
end

if exist('automated_pf_category','var')
    params.automated_pf_category = automated_pf_category;
end

if exist('notes_curation','var')
    cleanednotes_curation = regexprep(notes_curation, ',', ' ');
    params.notes_curation = cleanednotes_curation;
end

