function saveLedDetectionImage(imsavename, bkgdImage, ledXY, templateShapeXY, doesYAxisPointUp, has_explicit_masks, mask_from_mask_index)

if isempty(imsavename) 
  return
end

figpos = [10,10,800,800];
hfig = figure();
set(hfig,'Units','pixels','Position',figpos);
nimsplot = 1;
hax = createsubplots(1,nimsplot,0.05,hfig);
a = hax(1) ;
 
% plot background image in jet colormap
imagesc(bkgdImage,'parent',a,[0,255]);
axis(a,'image');
if doesYAxisPointUp ,
  axis(a,'xy');  % This means image will be upside-down from how Matlab normally displays images
else
  axis(a,'ij'); 
end
set(a, 'DataAspectRatio', [1 1 1]) ;
set(a, 'XLim', [0.5 size(bkgdImage,2)+0.5]) ;
set(a, 'YLim', [0.5 size(bkgdImage,1)+0.5]) ;

hold(a,'on');

% Plot LED template match outline
lo_corner_xy = ledXY - templateShapeXY/2 ;
hi_corner_xy = ledXY + templateShapeXY/2 ;
corners = [ lo_corner_xy(1) lo_corner_xy(2) ; ...
            hi_corner_xy(1) lo_corner_xy(2) ; ...
            hi_corner_xy(1) hi_corner_xy(2) ; ...
            lo_corner_xy(1) hi_corner_xy(2) ; ...
            lo_corner_xy(1) lo_corner_xy(2) ] ; 
x_data = corners(:,1)' ;
y_data = corners(:,2)' ;
line('Parent', a, 'XData', x_data, 'YData', y_data, 'Color', 'w', 'LineWidth', 3) ;
line('Parent', a, 'XData', x_data, 'YData', y_data, 'Color', 'k', 'LineWidth', 1) ;  % 0.5 is the default line width

% Plot LED template match center
line('Parent', a, ...
     'XData', ledXY(1), ...
     'YData', ledXY(2), ...
     'Marker', 's', ...
     'MarkerSize', 12, ...
     'MarkerEdgeColor', 'k', ...
     'MarkerFaceColor', 'w');
line('Parent', a, ...
     'XData', ledXY(1), ...
     'YData', ledXY(2), ...
     'Marker', 'x', ...
     'MarkerSize', 12, ...
     'MarkerEdgeColor', 'k', ...
     'MarkerFaceColor', 'none');

nr = size(bkgdImage, 1) ;
nc = size(bkgdImage, 2) ;
[mask_count, trimmed_mask_from_mask_index, trimmed_mask_lo_bound_in_frame_coords, ~, ~] = ...
  compute_trimmed_masks_and_bounds(has_explicit_masks, mask_from_mask_index, ledXY, nr, nc) ;

if has_explicit_masks ,
  for mask_index = 1 : mask_count ,
    trimmed_mask = trimmed_mask_from_mask_index(:,:,mask_index) ;
    boundary_from_island_index = bwboundaries(trimmed_mask) ;  % boundary_count x 2, in yx order
    boundary = boundary_from_island_index{1} ;  % hopefully there's only one
    boundary_mean = mean(boundary, 1) ; % 1x2, yx order
    line('Parent', a, ...
         'XData', trimmed_mask_lo_bound_in_frame_coords(2)+1+boundary(:,2), ...
         'YData', trimmed_mask_lo_bound_in_frame_coords(1)-1+boundary(:,1), ...
         'Color', 'w', ...
         'LineWidth', 3) ;
    line('Parent', a, ...
         'XData', trimmed_mask_lo_bound_in_frame_coords(2)+1+boundary(:,2), ...
         'YData', trimmed_mask_lo_bound_in_frame_coords(1)-1+boundary(:,1), ...
         'Color', 'k', ...
         'LineWidth', 1) ;
    text(a, ...
         trimmed_mask_lo_bound_in_frame_coords(2)+1+boundary_mean(2), ...
         trimmed_mask_lo_bound_in_frame_coords(1)+1+boundary_mean(1), ...
         sprintf('%d', mask_index), ...
         'Color', 'w', ...
         'FontWeight', 'bold', ...
         'HorizontalAlignment', 'center', ...
         'VerticalAlignment', 'middle') ;      
    text(a, ...
         trimmed_mask_lo_bound_in_frame_coords(2)+1+boundary_mean(2), ...
         trimmed_mask_lo_bound_in_frame_coords(1)+1+boundary_mean(1), ...
         sprintf('%d', mask_index), ...
         'Color', 'k', ...
         'HorizontalAlignment', 'center', ...
         'VerticalAlignment', 'middle') ;      
  end
end


title(a,'Maxvalue image and LED detection');
colormap(hfig,'jet');

try
  if exist(imsavename,'file'),
    try
      delete(imsavename);
    catch ME,
      warning('Could not delete file %s:\n %s',imsavename,getReport(ME));
    end
  end
  set(hfig,'Units','pixels','Position',figpos);
  save2png(imsavename,hfig);
catch ME,
  warning('Could not save to %s:\n%s',imsavename,getReport(ME));
end
