% Where does this script live?
this_script_path = mfilename('fullpath') ;
fly_disco_analysis_test_folder_path = fileparts(this_script_path) ;
fly_disco_analysis_folder_path = fileparts(fly_disco_analysis_test_folder_path) ;
fly_disco_folder_path = fileparts(fly_disco_analysis_folder_path) ;

cluster_billing_account_name = [] ;
user_name_for_configuration_purposes = 'bransonlab' ;
analysis_parameters = cell(1,0) ;
% analysis_parameters = ...
%          {'doautomaticchecksincoming',true,...
%           'doflytracking',true, ...
%           'doregistration',true,...
%           'doledonoffdetection',true,...
%           'dosexclassification',false,...
%           'dotrackwings',false,...
%           'docomputeperframefeatures',false,...
%           'docomputehoghofperframefeatures',false,...
%           'dojaabadetect',false,...
%           'docomputeperframestats',false,...
%           'doplotperframestats',false,...
%           'domakectraxresultsmovie',false,...
%           'doextradiagnostics',false,...
%           'doanalysisprotocol',false,...
%           'doautomaticcheckscomplete',false, ...
%           'domakeaptresultsmovie',false, ...
%           'doapt',false} ;
%settings_folder_path = fullfile(fly_disco_analysis_folder_path, 'settings-internal') ;  % for now, want to use internal settings
settings_folder_path = '/groups/branson/home/bransonlab/BransonFlyDiscoSettings/settings' ;
do_use_bqueue = true ;
do_actually_submit_jobs = true ;
do_try = true ;
do_reset_working_experiments_folder = true ;
do_run_caboose = true ;
submit_host_name = if_not_a_submit_host('submit.int.janelia.org') ;
initial_optional_argument_list = { ...
  'settingsdir', settings_folder_path, ...
  'do_try', do_try, ...
  'do_run_caboose', do_run_caboose } ;
optional_argument_list = horzcat(initial_optional_argument_list, analysis_parameters) ;

% Find the experiments
%s1 = loadAnonymous('/groups/branson/home/bransonlab/expdirs_VNC_20240711_VNC_passAandM_metadata_explist.mat') ;
%folder_path_from_experiment_index_1 = s1' ;
folder_path_from_experiment_index_1 = cell(0,1) ;
s2 = loadAnonymous('/groups/branson/home/bransonlab/expdirs_VNC_20240711_VNC2_passAandM_metadata_explist.mat') ;
folder_path_from_experiment_index_2 = s2' ;
folder_path_from_raw_experiment_index = vertcat(folder_path_from_experiment_index_1, folder_path_from_experiment_index_2) ;
folder_path_from_experiment_index = folder_path_from_raw_experiment_index ;

% Call the testing function to do the real work
run_transfero_FlyDiscoPipeline_wrapper_on_experiment_list(...
  folder_path_from_experiment_index, ...
  cluster_billing_account_name, ...
  user_name_for_configuration_purposes, ...
  do_use_bqueue, ...
  do_actually_submit_jobs, ...
  do_try, ...
  submit_host_name, ...
  optional_argument_list{:})

% Check for success in the ACC output files
did_succeed_from_experiment_folder_index = cellfun(@did_analysis_of_experiment_folder_succeed, folder_path_from_experiment_index)
did_all_succeed = all(did_succeed_from_experiment_folder_index) ;
if did_all_succeed ,
  fprintf('All finished.\n') ;
else
  fprintf('Some failed.\n') ;  
end
