% This isn't a proper test b/c it doesn't check whether anything worked

% Where does this script live?
this_script_path = mfilename('fullpath') ;
fly_disco_analysis_test_folder_path = fileparts(this_script_path) ;
fly_disco_analysis_folder_path = fileparts(fly_disco_analysis_test_folder_path) ;
fly_disco_folder_path = fileparts(fly_disco_analysis_folder_path) ;

cluster_billing_account_name = 'branson' ;
user_name_for_configuration_purposes = 'bransonlab' ;
% analysis_parameters = cell(1,0) ;
% analysis_parameters = ...
%          {'doautomaticchecksincoming',true,...
%           'doflytracking',true, ...
%           'doregistration',true,...
%           'doledonoffdetection',true,...
%           'dosexclassification',true,...
%           'dotrackwings',false,...
%           'docomputeperframefeatures',true,...
%           'docomputehoghofperframefeatures',false,...
%           'dojaabadetect',true,...
%           'docomputeperframestats',false,...
%           'doplotperframestats',false,...
%           'domakectraxresultsmovie',true,...
%           'doextradiagnostics',false,...
%           'doanalysisprotocol',true,...
%           'doautomaticcheckscomplete',false, ...
%           'doapt',false} ;
settings_folder_path = fullfile(fly_disco_analysis_folder_path, 'settings-internal') ;  % for now, want to use internal settings
optional_argument_list = { ...
  'settingsdir', settings_folder_path, ...
  'do_try', false } ;
do_use_bqueue = false ;
do_actually_submit_jobs = false ;
do_try = false ;
do_reset_working_experiments_folder = true ;
submit_host_name = if_not_a_submit_host('submit.int.janelia.org') ;

read_only_experiments_folder_path = fullfile(fly_disco_folder_path, 'example-experiments', 'early-multibubble-experiments-with-tracking-read-only') ;
working_experiments_folder_path = fullfile(fly_disco_folder_path, 'example-experiments', 'early-multibubble-experiments-with-tracking') ;

% Recopy the working folder from the read-only one
if do_reset_working_experiments_folder || ~exist(working_experiments_folder_path, 'dir')
  fprintf('Resetting working experiments folder...\n') ;
  tic_id = tic() ;
  reset_experiment_working_copies(working_experiments_folder_path, read_only_experiments_folder_path) ;
  elapsed_time = toc(tic_id) ;
  fprintf('Elapsed time: %g s\n', elapsed_time) ;
end

% Find the experiments
folder_path_from_experiment_index = find_experiment_folders(working_experiments_folder_path) ;

% % Run the script under test
% experiment_count = length(folder_path_from_experiment_index) ;
% for experiment_index = 1 : experiment_count ,
%     experiment_folder_path = folder_path_from_experiment_index{experiment_index} ;
%     fprintf('Running transfero_FlyDiscoPipeline_wrapper on experiment index %d...\n', experiment_index) ;
%     transfero_FlyDiscoPipeline_wrapper(experiment_folder_path, user_name_for_configuration_purposes, optional_argument_list{:}) ;
% end

% Call the testing function to do the real work
run_transfero_FlyDiscoPipeline_wrapper_on_experiment_list(...
  folder_path_from_experiment_index, ...
  cluster_billing_account_name, ...
  user_name_for_configuration_purposes, ...
  do_use_bqueue, ...
  do_actually_submit_jobs, ...
  do_try, ...
  submit_host_name, ...
  optional_argument_list{:})
