function bioFigureHelpMenu(hFig, funLabel, funRefPage)
%BIOFIGUREHELPMENU Updates the Help menu to Bioinfo specific help menu.
%
%   BIOFIGUREHELPMENU(HFIG, FUNLABEL, FUNREFPAGE) updates the Help menu in
%   HFIG to be Bioinformatics Toolbox specific help menu: 
%       Bioinformatics Toolbox Help
%       FunctionLabel Help
%       Demos
%       Send Feedback

% Copyright 2009-2011 The MathWorks, Inc.

% Repair "Help" menu
%hw = findall(hFig, 'Type', 'uimenu', 'Label', '&Help');
hw = findall(hFig, 'Type', 'uimenu', 'Tag', 'figMenuHelp');
delete(get(hw,'children'));

%== Bioinfo help
uimenu(hw, 'Label',    'Bioinformatics Toolbox Help',...
           'Position', 1,...
           'Callback', 'helpview(fullfile(docroot,''toolbox'',''bioinfo'',''bioinfo.map''),''bioinfo_product_page'')')
%==Function help
refLinkCB = sprintf('helpview(fullfile(docroot,''toolbox'',''bioinfo'',''bioinfo.map''), ''%s'')',...
                               funRefPage);
uimenu(hw, 'Label',   [funLabel, ' Help'],...
           'Position', 2,...
           'Callback', refLinkCB)
%== Bioinfo Demos
uimenu(hw, 'Label', 'Demos',...
           'Position', 3,...
           'Separator','on',...
           'Callback', 'demo(''toolbox'',''bioinfo'')')   
%== Send feedback
tlbx = ver('bioinfo');
mailstr = ['web(''mailto:bioinfo-feedback@mathworks.com?subject=',...
           'Feedback%20for%20' funLabel '%20in%20Bioinformatics',...
           '%20Toolbox%20',tlbx(1).Version,''')'];
uimenu(hw,  'Label', 'Send Feedback',...
            'Position',4,...
            'Separator','on',...
            'Callback',mailstr);
end
