do_use_bqueue = false ;
do_actually_submit_jobs = true ;
cluster_billing_account_name = 'branson' ;  % used for billing the jobs
do_force_analysis = false ;
analysis_parameters = cell(1,0) ;
% analysis_parameters = ...
%          {'doautomaticchecksincoming',true,...
%           'doflytracking',true, ...
%           'doregistration',true,...
%           'doledonoffdetection',true,...
%           'dosexclassification',true,...
%           'dotrackwings',false,...
%           'docomputeperframefeatures',true,...
%           'docomputehoghofperframefeatures',false,...
%           'dojaabadetect',true,...
%           'docomputeperframestats',false,...
%           'doplotperframestats',false,...
%           'domakectraxresultsmovie',true,...
%           'doextradiagnostics',false,...
%           'doanalysisprotocol',true,...
%           'doautomaticcheckscomplete',false};

% Where does this script live?
this_script_path = mfilename('fullpath') ;
this_folder_path = fileparts(this_script_path) ;
fly_disco_analysis_folder_path = fileparts(this_folder_path) ;
settings_folder_path = fullfile(fly_disco_analysis_folder_path, 'settings') ;
read_only_experiments_folder_path = fullfile(fly_disco_analysis_folder_path, 'too-much-memory-example-experiments-blank-slate-read-only') ;
working_experiments_folder_path = fullfile(fly_disco_analysis_folder_path, 'too-much-memory-example-experiments-blank-state') ;

% Delete the destination folder
if exist(working_experiments_folder_path, 'file') ,
    return_code = system_from_list_with_error_handling({'rm', '-rf', working_experiments_folder_path}) ;
end

% Recopy the test folder from the template
fprintf('Resetting working experiments folder...\n') ;
reset_experiment_working_copies(working_experiments_folder_path, read_only_experiments_folder_path) ;

% Find the experiments
folder_path_from_experiment_index = find_experiment_folders(working_experiments_folder_path) ;

% Run the script under test
fprintf('Running goldblum_analyze_experiment_folders...\n') ;
goldblum_analyze_experiment_folders(folder_path_from_experiment_index, settings_folder_path, cluster_billing_account_name, ...
                           do_force_analysis, do_use_bqueue, do_actually_submit_jobs, analysis_parameters)
