% Test by copying some experiments to a single Branson Lab rig machine, then
% using goldblum to suck the data back and analyze the experiments

% Set some options
do_transfer_data_from_rigs = true ;
do_use_bqueue = true ;
do_actually_submit_jobs = true ;
analysis_parameters = ...
         {'forcecompute',false,...
          'doautomaticchecksincoming',true,...
          'doflytracking',true, ...
          'doregistration',true,...
          'doledonoffdetection',true,...
          'dosexclassification',true,...
          'dotrackwings',false,...
          'docomputeperframefeatures',true,...
          'docomputehoghofperframefeatures',false,...
          'dojaabadetect',true,...
          'docomputeperframestats',false,...
          'doplotperframestats',false,...
          'domakectraxresultsmovie',true,...
          'doextradiagnostics',false,...
          'doanalysisprotocol',true,...
          'doautomaticcheckscomplete',false};

% Figure out where this script lives in the filesystem
this_script_path = mfilename('fullpath') ;
this_folder_path = fileparts(this_script_path) ;

% This stuff goes into the per-lab configuration that goldblum uses
cluster_billing_account_name = 'branson' ;
remote_host_name_from_rig_index = { 'arrowroot.hhmi.org', 'beet.hhmi.org', 'carrot.hhmi.org', 'daikon.hhmi.org' } ;
remote_user_name = 'bransonk' ;
rig_user_name_from_rig_index = repmat({remote_user_name}, [1 4]) ;
remote_data_root_folder_path = '/cygdrive/e/flydisco_data' ;
data_folder_path_from_rig_index = repmat({remote_data_root_folder_path}, [1 4]) ;
destination_folder_path = '/groups/branson/bransonlab/flydisco_data' ;
settings_folder_path = fullfile(this_folder_path, 'FlyDiscoAnalysis/settings') ;
does_use_per_user_folders = false ;

% Specify the "per-lab" configuration here
per_lab_configuration = struct() ;
per_lab_configuration.cluster_billing_account_name = cluster_billing_account_name ;
per_lab_configuration.host_name_from_rig_index = remote_host_name_from_rig_index ;
per_lab_configuration.rig_user_name_from_rig_index = rig_user_name_from_rig_index ;
per_lab_configuration.data_folder_path_from_rig_index = data_folder_path_from_rig_index ;
per_lab_configuration.destination_folder = destination_folder_path ;    
per_lab_configuration.settings_folder_path = settings_folder_path ;
per_lab_configuration.does_use_per_user_folders = does_use_per_user_folders ;

% Run goldblum
goldblum(do_transfer_data_from_rigs, do_use_bqueue, do_actually_submit_jobs, analysis_parameters, per_lab_configuration) ;        
