%% script_plot_control_onceiling_over_time
% Plot per-experiment onceiling % and walking-while-onceiling % for
% YNA_K_162984 controls over time, colored by screen type (VNC/VNC2/VNC3).
% Each dot = one experiment.
%
% Requires:
%   onceiling_resnet_v2_summary.mat in datadir (generated by computing
%   per-experiment stats from scores_onceiling_resnet_v2.mat and
%   scores_Walk2.mat across all 624 control experiments).

datadir = '/groups/branson/home/robiea/Projects_data/FlyDisco/Bubble_data/20260225_VNC23controldata4onceilingwalkexplore/';
plotdir = '/groups/branson/home/robiea/Projects_data/FlyDisco/Locomotion_analysis/claudeplots_20260313_onceiling/';

load(fullfile(datadir, 'onceiling_resnet_v2_summary.mat'), ...
    'expnames', 'pct_onceiling', 'pct_walk_onceiling', 'dates_dt', 'screen_type');

if ~isfolder(plotdir), mkdir(plotdir); end

% Colors for screen types
colors = struct('VNC', [0.2 0.6 0.2], 'VNC2', [0.2 0.4 0.8], 'VNC3', [0.8 0.3 0.2]);
st_list = {'VNC', 'VNC2', 'VNC3'};

%% Plot 1: % onceiling over time (each dot = one experiment)
figure('Position', [100 100 1200 500]);
hold on;

for si = 1:3
    st = st_list{si};
    idx = strcmp(screen_type, st);
    scatter(dates_dt(idx), pct_onceiling(idx), 25, colors.(st), 'filled', 'MarkerFaceAlpha', 0.6);
end

xlabel('Date');
ylabel('% frames onceiling (ResNet v2)', 'Interpreter', 'none');
title('Control (YNA\_K\_162984) onceiling % over time', 'Interpreter', 'none');
legend(st_list, 'Location', 'best');
ax = gca;
ax.XAxis.TickLabelFormat = 'MMM yyyy';
xtickangle(45);
ylim([0 max(pct_onceiling)*1.05]);
grid on;

exportgraphics(gcf, fullfile(plotdir, 'ctrl_onceiling_pct_over_time.png'));
exportgraphics(gcf, fullfile(plotdir, 'ctrl_onceiling_pct_over_time.pdf'), 'ContentType', 'vector');

%% Plot 2: % walking-while-onceiling over time (each dot = one experiment)
figure('Position', [100 100 1200 500]);
hold on;

for si = 1:3
    st = st_list{si};
    idx = strcmp(screen_type, st);
    scatter(dates_dt(idx), pct_walk_onceiling(idx), 25, colors.(st), 'filled', 'MarkerFaceAlpha', 0.6);
end

xlabel('Date');
ylabel('% frames walking AND onceiling (ResNet v2)', 'Interpreter', 'none');
title('Control (YNA\_K\_162984) walking-while-onceiling % over time', 'Interpreter', 'none');
legend(st_list, 'Location', 'best');
ax = gca;
ax.XAxis.TickLabelFormat = 'MMM yyyy';
xtickangle(45);
ylim([0 max(pct_walk_onceiling)*1.05]);
grid on;

exportgraphics(gcf, fullfile(plotdir, 'ctrl_walk_onceiling_pct_over_time.png'));
exportgraphics(gcf, fullfile(plotdir, 'ctrl_walk_onceiling_pct_over_time.pdf'), 'ContentType', 'vector');

%% Print summary stats
fprintf('\nSummary:\n');
for si = 1:3
    st = st_list{si};
    idx = strcmp(screen_type, st);
    fprintf('  %s (n=%d): onceiling median=%.1f%%, mean=%.1f%%, max=%.1f%%\n', ...
        st, sum(idx), median(pct_onceiling(idx)), mean(pct_onceiling(idx)), max(pct_onceiling(idx)));
    fprintf('           walk+onceiling median=%.1f%%, mean=%.1f%%, max=%.1f%%\n', ...
        median(pct_walk_onceiling(idx)), mean(pct_walk_onceiling(idx)), max(pct_walk_onceiling(idx)));
end
