%% test_pipeline_locostatsperexp_onfloor.m
% Verify that FlyDiscoComputeLocomotionMetrics produces locostatsperexp_onfloor.mat
% matching the reference generated by test_onfloor_filtering.m (which validates
% correctness via post-hoc filtering).
%
% Prerequisites:
%   - locostatsperexp_onfloor_reference.mat must exist in expdir
%     (generated by test_onfloor_filtering.m, then renamed)
%   - scores_nottracking.mat must exist in expdir

modpath;

%% Setup
settingsdir = '/groups/branson/home/robiea/Code_versioned/BransonFlyDiscoSettings/settings';
analysis_protocol = '20260326_flybubble_LED_VNC2';
expdir = '/groups/branson/home/robiea/Projects_data/FlyDisco/Bubble_data/20260325_testingOnFloorfiltering/VNC2_YNA_K_162984_RigB_20230913T100609';

fprintf('=== Test: Pipeline locostatsperexp_onfloor ===\n');
fprintf('Experiment: %s\n', expdir);
fprintf('Analysis protocol: %s\n\n', analysis_protocol);

%% Step 1: Run the pipeline stage
fprintf('--- Running FlyDiscoComputeLocomotionMetrics ---\n');
FlyDiscoComputeLocomotionMetrics(expdir, ...
    'settingsdir', settingsdir, ...
    'analysis_protocol', analysis_protocol, ...
    'forcecompute', true);
fprintf('Pipeline stage complete.\n\n');

%% Step 2: Load pipeline output and reference
% Pipeline output filename is set in dataloc_params: locostatsperexp_onfloor.mat
pipeline_file = fullfile(expdir, 'locostatsperexp_onfloor.mat');
reference_file = fullfile(expdir, 'locostatsperexp_onfloor_reference.mat');

assert(exist(pipeline_file, 'file') == 2, 'Pipeline output not found: %s', pipeline_file);
assert(exist(reference_file, 'file') == 2, 'Reference file not found: %s', reference_file);

P = load(pipeline_file);
if isfield(P, 'locostatsperexp'), pipeline_stats = P.locostatsperexp; else, pipeline_stats = P; end

R = load(reference_file);
if isfield(R, 'locostatsperexp'), ref_stats = R.locostatsperexp; else, ref_stats = R; end

pipeline_fields = fieldnames(pipeline_stats);
ref_fields = fieldnames(ref_stats);

fprintf('Pipeline fields: %d\n', numel(pipeline_fields));
fprintf('Reference fields: %d\n\n', numel(ref_fields));

%% Step 3: Field-by-field comparison
fprintf('=== TEST 1: Pipeline output matches reference ===\n');

missing_in_pipeline = setdiff(ref_fields, pipeline_fields);
if ~isempty(missing_in_pipeline)
    fprintf('Fields in REFERENCE but not in PIPELINE (%d):\n', numel(missing_in_pipeline));
    for i = 1:numel(missing_in_pipeline)
        fprintf('  %s\n', missing_in_pipeline{i});
    end
end

extra_in_pipeline = setdiff(pipeline_fields, ref_fields);
if ~isempty(extra_in_pipeline)
    fprintf('Fields in PIPELINE but not in REFERENCE (%d):\n', numel(extra_in_pipeline));
    for i = 1:numel(extra_in_pipeline)
        fprintf('  %s\n', extra_in_pipeline{i});
    end
end

shared_fields = intersect(ref_fields, pipeline_fields);
fprintf('Shared fields: %d\n', numel(shared_fields));

n_match = 0;
n_mismatch = 0;
tol = 1e-10;

for i = 1:numel(shared_fields)
    fn = shared_fields{i};
    rv = ref_stats.(fn);
    pv = pipeline_stats.(fn);

    match = true;
    details = '';

    for stat = {'mean', 'std', 'Z'}
        s = stat{1};
        if isfield(rv, s) && isfield(pv, s)
            r = rv.(s);
            p = pv.(s);
            if isnan(r) && isnan(p)
                % both NaN, OK
            elseif abs(r - p) > tol
                match = false;
                details = [details, sprintf(' %s: ref=%.6g pipe=%.6g', s, r, p)]; %#ok<AGROW>
            end
        elseif isfield(rv, s) ~= isfield(pv, s)
            match = false;
            details = [details, sprintf(' %s: field missing in one', s)]; %#ok<AGROW>
        end
    end

    if match
        n_match = n_match + 1;
    else
        n_mismatch = n_mismatch + 1;
        fprintf('  MISMATCH: %s |%s\n', fn, details);
    end
end

if n_mismatch == 0
    fprintf('PASS: All %d/%d shared fields match\n', n_match, numel(shared_fields));
else
    fprintf('FAIL: %d mismatches out of %d shared fields\n', n_mismatch, numel(shared_fields));
end

%% Step 4: Sanity checks
fprintf('\n=== TEST 2: Sanity checks ===\n');

% Check Z counts > 0
n_zero_Z = 0;
for i = 1:numel(pipeline_fields)
    fn = pipeline_fields{i};
    if isfield(pipeline_stats.(fn), 'Z') && pipeline_stats.(fn).Z == 0
        n_zero_Z = n_zero_Z + 1;
    end
end
if n_zero_Z == 0
    fprintf('PASS: All fields have Z > 0\n');
else
    fprintf('INFO: %d fields have Z == 0\n', n_zero_Z);
end

% Check no unexpected NaN in mean/std when Z > 0
n_bad_nan = 0;
for i = 1:numel(pipeline_fields)
    fn = pipeline_fields{i};
    s = pipeline_stats.(fn);
    if isfield(s, 'Z') && s.Z > 0
        if isfield(s, 'mean') && isnan(s.mean)
            n_bad_nan = n_bad_nan + 1;
            fprintf('  NaN mean with Z>0: %s (Z=%d)\n', fn, s.Z);
        end
        if isfield(s, 'std') && isnan(s.std)
            n_bad_nan = n_bad_nan + 1;
            fprintf('  NaN std with Z>0: %s (Z=%d)\n', fn, s.Z);
        end
    end
end
if n_bad_nan == 0
    fprintf('PASS: No unexpected NaN values\n');
else
    fprintf('FAIL: %d fields with NaN despite Z > 0\n', n_bad_nan);
end

% Check field naming convention
n_bad_names = 0;
for i = 1:numel(pipeline_fields)
    fn = pipeline_fields{i};
    if ~contains(fn, '__LEDon__') && ~contains(fn, '__LEDoff__')
        n_bad_names = n_bad_names + 1;
        fprintf('  Unexpected field name: %s\n', fn);
    end
end
if n_bad_names == 0
    fprintf('PASS: All field names contain __LEDon__ or __LEDoff__\n');
else
    fprintf('INFO: %d fields without LED condition in name\n', n_bad_names);
end

%% Summary
fprintf('\n=== SUMMARY ===\n');
n_total_fail = n_mismatch + numel(missing_in_pipeline) + numel(extra_in_pipeline);
if n_total_fail == 0
    fprintf('ALL TESTS PASSED\n');
else
    fprintf('ISSUES: %d mismatches, %d missing, %d extra\n', ...
        n_mismatch, numel(missing_in_pipeline), numel(extra_in_pipeline));
end
