function A = affineTransformMatrixFromOffsetsAndScale(offX,offY,offTheta,scale)
costheta = cos(offTheta) ; 
sintheta = sin(offTheta) ;
Offset = [    1     0  0 ; ...
              0     1  0 ; 
           offX  offY  1 ] ;
Rotation = [  costheta  sintheta  0 ; ...
             -sintheta  costheta  0 ; ...
                     0         0  1 ] ;
Scale = [ scale      0  0 ; ...
              0  scale  0 ; ...
              0      0  1 ] ;
A = Offset * Rotation * Scale ;
% A = [1 0 0; 0 1 0; offX offY 1] * ...
%   [costheta sintheta 0; -sintheta costheta 0; 0 0 1] * ...
%   [scale 0 0; 0 scale 0; 0 0 1];
end  % function
