function registration_params_cell = filterRegistrationParamsForFlyTrackerMethod(registration_params) 
% Collect things from registration_params, make a cell array suitable for
% passing to determineRegistrationTransformForFlyTrackerMethodCore().
% This is a pure function.

all_field_names_to_keep = { ...
  'bkgdImage',...
  'nRotations',...
  'minTemplateFeatureStrength',...
  'maxDistCornerFrac_BowlLabel',...
  'nBowlMarkers',...
  'bowlMarkerTemplate',...
  'debug',...
  'useNormXCorr', ...
  'flytrackerCalibration' } ;
field_names = fieldnames(registration_params) ;
present_field_names_to_keep = intersect(field_names, all_field_names_to_keep) ;
present_field_names_to_drop = setdiff(field_names, present_field_names_to_keep);
filtered_registration_params = rmfield(registration_params, present_field_names_to_drop) ;
registration_params_cell = struct2paramscell(filtered_registration_params);
